apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: entandos.crd.entando.org
spec:
  group: entando.org
  names:
    kind: Entando
    plural: entandos
    singular: entando
#  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    entandoNamespace:
                      type: string
                  required:
                    - entandoNamespace
              required:
                - parameters

