apiVersion: entando.org/v1
kind: EntandoApp
metadata:
  namespace: entando
  name: app1
spec:
  environmentVariables:
    - name: SPRING_PROFILES_ACTIVE
      value: "default,swagger"
  dbms: postgresql
  ingressHostName: quickstart.localhost.nip.io
  standardServerImage: tomcat
  replicas: 1
