apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: entandoapps.crdx.entando.org
spec:
  group: crdx.entando.org
  names:
    kind: EntandoApp
    plural: entandoapps
#  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    entandoNamespace:
                      type: string
                  required:
                    - entandoNamespace
              required:
                - parameters

